### ISSUE TITLE
4 - As a player, I want to watch the food cook so that I can have an immersive cooking experience 🍳

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#10]
**Acceptance Criteria**
- [x] Proteins like chicken and tofu should brown the longer they are in the pan; onions should become more clear as they cook

**Tasks**
- [x] Create art assets for cooked chicken, cooked tofu, and pan/pot ❤
- [x] Create 2-3 random strips for both the chicken and tofu
- [x] Create a lid for the pot that will be dragged on and off
