### ISSUE TITLE
6 - As a player, I want to be taught by someone from the culture so that I gain cultural context about the different things I’m learning 👩‍🏫

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#11]
**Acceptance Criteria**
- [x] Game should include a mentor that guides the player's cooking
- [x] Mentor should give general instructions that the player has freedom to be creative in

**Tasks**
- [x] Create different art artifacts of expressions for the Mentor
- [x] Create neutral expression and headshot
- [x] Create happy expression and headshot
- [x] Create disappointed expression and headshot
- [x] Create ___ expression and headshot
