### ISSUE TITLE
7 - As a player, I want text to appear on the screen so I can see what my guide is saying 📖

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#12]
**Acceptance Criteria**
- [x] Text should appear in a scrolling manner so it seems like the mentor is talking in real time
- [x] Text should be shown in a box at the bottom or top of screen
- [x] Mentor's face should be shown with text

**Tasks**
- [x] Create headshots of the Mentor that will be shown with the text
