### ISSUE TITLE
5 - As a player, I want to learn about how spices are cooked to create different flavors 🥣

### ISSUE THREAD

**Issue by Patrickode** [Patrickode/taste-of-culture#2]
**Acceptance Criteria**
- [x] A discussion about how spices are mixed and what different mixtures are used should be included
- [x] Player should be able to create their own spice mix

**Tasks**
- [x] **Research - Spice flavors** 🧡
Research the flavors added by each spice to allow for a flavor portfolio based on what the dish should be and what the players wants it to be. (need to add the spices as well)
- [x] Garlic
- [x] Chili (powder?)
- [x] Turmeric
- [x] Cumin
- [x] Ginger
- [x] Black Peppercorn
- [x] Salt
- [x] Update Document with Findings
- [x] Create Own Spice Values
