### ISSUE TITLE
1 - As a player, I want to use a knife so I can cut ingredients for the dish 🔪

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#3]
**Acceptance Criteria**
- [x] When appropriate, the player should be able to grab knife (snapped to cursor or click and hold?)
- [x] For cutting bigger items, the player should click to lower the knife, and move the mouse to slice the ingredient.

**Tasks**
 - **Slicing Chicken & Tofu**
   - [x] Animation for using knife. 💜❤
   - [x] Assets for chicken (cut & uncut), tofu (cut & uncut), knife, cutting board. ❤
   - [x] Mouse controls for slicing. 💙
   - [x] Code for cutting assets.  💙💜
   - [x] Asking professor questions about process. 💛

**Solution Tasks**
   - [x] Guidelines for making cuts. 
   - [x] "Margin of Error". 💙💜
