### ISSUE TITLE
2 - As a player, I want to use a knife so I can chop ingredients for the dish 🔪

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#5]
**Acceptance Criteria**
 - [x] For smaller items, the player should click once to quickly chop the ingredient.

**Tasks**
 - **Cutting Vegetables**
   - [x] Code for chopping mechanic. 💙💜
   - [x] Create art assets for onion & tomato. ❤
   - [x] Create chunks so that after the veggies have been cut they fall into chunks. ❤
   - [x] Create asset for a chopping knife ❤
   - [x] Add chopping animations in Unity 💜

**Solution Tasks**
  - [x] Movement restrictions so that player only moves ingredient when they've completed the required steps. 💙💜
