### ISSUE TITLE
3 - As a player, I want to see a demonstration of what to do, so even if there’s room for experimentation, I know what to do 👨‍🏫

### ISSUE THREAD

**Issue by crfair** [Patrickode/taste-of-culture#9]
**Acceptance Criteria**
- [x] Have something that shows the player what they will be doing based on the section of cooking 

**Tasks**
- [x] Create a gif of the actions players can do for slicing the chicken/tofu  ❤
- [x] Create a gif of the actions players can do for cutting the vegetables ❤
